// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Models
{
    [Table("Config")]
    public partial class Config
    {
        [Key]
        [StringLength(255)]
        public string Key { get; set; }
        [Column(TypeName = "ntext")]
        public string Value { get; set; }
        public string Description { get; set; }
    }
}