// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models
{
    [Table("OrderDetailProduct")]
    public partial class OrderDetailProduct
    {
        [Key]
        public int OrderID { get; set; }
        [Key]
        public int ProductID { get; set; }
        public int? Quantity { get; set; }
        public double? Price { get; set; }
        [StringLength(255)]
        public string Avatar { get; set; }
        [StringLength(255)]
        public string Title { get; set; }

        // [ForeignKey("OrderID")]
        // [InverseProperty("OrderDetails")]
        // public virtual Order Order { get; set; }
        // [ForeignKey("ProductID")]
        // [InverseProperty("OrderDetails")]
        // public virtual Product Product { get; set; }
    }
}