// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models
{
    [Table("Order")]
    public partial class Order
    {
        public Order()
        {
            OrderDetails = new HashSet<OrderDetail>();
        }

        [Key]
        public int OrderID { get; set; }
        [StringLength(50)]
        public string FullName { get; set; }
        [StringLength(50)]
        public string Mobile { get; set; }
        [StringLength(255)]
        public string Address { get; set; }
        public double? Total { get; set; }
        public double? Bonus { get; set; }
        public double? Amount { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
        public int? OrderStatus { get; set; }
        public bool? ConfirmStatus { get; set; }
        public bool? ChargeStatus { get; set; }
        public int? DeliveStatus { get; set; }
        public int? ClientID { get; set; }

        [ForeignKey("ClientID")]
        [InverseProperty("Orders")]
        public virtual Client Client { get; set; }
        [InverseProperty("Order")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }

    public partial class OrderMoMo
    {
        [Key]
        public int OrderID { get; set; }
        public string FullName { get; set; }
        public string OrderInfo { get; set; }
        public double? Amount { get; set; }
        public string MomoCode { get; set; }
        public string ReturnUrl { get; set; }
    }
}