// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models
{
    [Table("RequestSupply")]
    public partial class RequestSupply
    {

        [Key]
        public int ID { get; set; }
        public int ProductID { get; set; }
        [StringLength(50)]
        public string CreateBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
        [StringLength(255)]
        public string Supplier { get; set; }
        public int? QuantityRequestSupply { get; set; }
        public double? UnitPrice { get; set; }
        public double? Total { get; set; }
        public bool? Status { get; set; }
        
    }

    public partial class RequestSupplyProduct
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        [StringLength(50)]
        public string CreateBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
        [StringLength(255)]
        public string Supplier { get; set; }
        public int? QuantityRequestSupply { get; set; }
        public double? UnitPrice { get; set; }
        public double? Total { get; set; }
        public bool? Status { get; set; }
        
        [StringLength(255)]
        public string Avatar { get; set; }
        [StringLength(255)]
        public string Title { get; set; }
        public double? Price { get; set; }
        public int? Quantity { get; set; }
    }
}